-- drop index idx_created_at_utc_posts;
-- drop table posts;
-- drop table users;

create table if not exists users
(
    "userId" bigint not null,
    "username" text,
    "menuId" int,
    "lat" double precision,
	"lon" double precision,
	"geom" geometry(POINT, 4326),
	"createdAtUtc" timestamp without time zone not null default (now() at time zone 'utc'),

    primary key ("userId")
);

create table if not exists posts
(
    "postId" bigint generated by default as identity primary key,
    "userId" bigint not null references "users" ("userId"),
    "text" text,
    "lat" double precision,
	"lon" double precision,
	"geom" geometry(POINT, 4326),
	"createdAtUtc" timestamp without time zone not null default (now() at time zone 'utc')
);

create index if not exists idx_created_at_utc_posts on "posts"("createdAtUtc");
